apiVersion: v1alpha1
kind: Role
metadata:
  name: my-docs-role-view
  labels:
    halo.run/role-template: "true"
  annotations:
    rbac.authorization.halo.run/module: "文档管理"
    rbac.authorization.halo.run/display-name: "文档查看"
    rbac.authorization.halo.run/ui-permissions: |
      ["plugin:my-docs:libraries:view"]
rules:
  - apiGroups: ["docs.halo.run"]
    resources: ["doclibraries", "docs"]
    verbs: ["get", "list"]
---
apiVersion: v1alpha1
kind: Role
metadata:
  name: my-docs-role-manage
  labels:
    halo.run/role-template: "true"
  annotations:
    rbac.authorization.halo.run/dependencies: |
      ["my-docs-role-view"]
    rbac.authorization.halo.run/module: "文档管理"
    rbac.authorization.halo.run/display-name: "文档管理"
    rbac.authorization.halo.run/ui-permissions: |
      ["plugin:my-docs:libraries:manage"]
rules:
  - apiGroups: ["docs.halo.run"]
    resources: ["doclibraries", "docs"]
    verbs: ["*"]
  - apiGroups: ["console.api.docs.halo.run"]
    resources: ["docs"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "create", "update", "patch"]
---
apiVersion: v1alpha1
kind: Role
metadata:
  name: my-docs-role-public
  labels:
    halo.run/role-template: "true"
    halo.run/hidden: "true"
    rbac.authorization.halo.run/aggregate-to-anonymous: "true"
rules:
  - apiGroups: ["api.docs.halo.run"]
    resources: ["libraries", "docs", "trees"]
    verbs: ["get", "list"]
  - nonResourceURLs: ["/apis/api.docs.halo.run/v1alpha1/**"]
    verbs: ["get"]
