apiVersion: v1alpha1
kind: Setting
metadata:
  name: my-docs-settings
spec:
  forms:
    - group: basic
      label: 基础设置
      formSchema:
        - $formkit: select
          name: defaultSort
          label: 默认排序
          value: priorityAsc
          options:
            - label: 排序权重升序
              value: priorityAsc
            - label: 创建时间倒序
              value: createdDesc
            - label: 标题升序
              value: titleAsc
        - $formkit: number
          name: pageSize
          label: 每页数量
          value: 20
          validation: required|min:5|max:100
        - $formkit: text
          name: defaultLibraryName
          label: 默认文档库
          value: ""
        - $formkit: select
          name: renderContentTheme
          label: 内容主题
          value: light
          options:
            - label: Light
              value: light
            - label: Dark
              value: dark
            - label: WeChat
              value: wechat
            - label: Ant Design
              value: ant-design
        - $formkit: text
          name: renderCodeTheme
          label: 代码主题
          value: github
        - $formkit: switch
          name: renderLineNumber
          label: 代码行号
          value: false
        - $formkit: switch
          name: renderAutoSpace
          label: 自动空格
          value: false
        - $formkit: switch
          name: renderGfmAutoLink
          label: 自动链接
          value: true
        - $formkit: switch
          name: renderFootnotes
          label: 脚注
          value: true
        - $formkit: switch
          name: renderMark
          label: Mark 标记
          value: false
        - $formkit: switch
          name: renderFixTermTypo
          label: 术语修正
          value: false
        - $formkit: switch
          name: renderParagraphBeginningSpace
          label: 段首空两格
          value: false
        - $formkit: switch
          name: renderCodeBlockPreview
          label: 代码块即时渲染
          value: true
        - $formkit: switch
          name: renderMathBlockPreview
          label: 公式块即时渲染
          value: true
