apiVersion: v1alpha1
kind: Setting
metadata:
  name: my-docs-settings
spec:
  forms:
    - group: basic
      label: 基础设置
      formSchema:
        - $formkit: select
          name: defaultSort
          label: 默认排序
          value: priorityAsc
          options:
            - label: 排序权重升序
              value: priorityAsc
            - label: 创建时间倒序
              value: createdDesc
            - label: 标题升序
              value: titleAsc
        - $formkit: number
          name: pageSize
          label: 每页数量
          value: 20
          validation: required|min:5|max:100
        - $formkit: text
          name: defaultLibraryName
          label: 默认文档库
          value: ""
