# Refer https://docs.halo.run/developer-guide/plugin/basics/manifest

apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  # The name defines how the plugin is invoked, A unique name
  name: my-docs
spec:
  enabled: true
  requires: ">=2.25.0"
  author:
    name: tsdaer
    website: https://github.com/tsdaer
  logo: logo.svg
  homepage: https://github.com/tsdaer/plugin-my-docs#readme
  repo: https://github.com/tsdaer/plugin-my-docs
  issues: https://github.com/tsdaer/plugin-my-docs/issues
  displayName: "文档"
  description: "为 Halo 网站添加文档（知识库）功能：按库与层级组织内容，提供带侧边目录树的文档阅读界面。"
  settingName: "my-docs-settings"
  configMapName: "my-docs-configmap"
  license:
    - name: "GPL-3.0"
      url: "https://github.com/tsdaer/plugin-my-docs/blob/master/LICENSE"
